service: bdr-lead-pipeline

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  region: us-east-1  # Cheapest region
  memorySize: 256    # Minimum memory for cost optimization
  timeout: 300       # 5 minutes max
  environment:
    MAX_LEADS: 10
    MIN_SCORE: 0.6
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: "arn:aws:logs:*:*:*"
        - Effect: Allow
          Action:
            - secretsmanager:GetSecretValue
          Resource: "arn:aws:secretsmanager:*:*:secret:bdr-pipeline-*"

functions:
  fetch-leads:
    handler: lambda_functions/fetch_leads.lambda_handler
    memorySize: 256
    timeout: 60
    environment:
      APOLLO_API_KEY: ${ssm:/bdr-pipeline/apollo-api-key}
    events:
      - schedule:
          rate: cron(0 9 * * ? *)  # Run daily at 9 AM UTC

  process-leads:
    handler: lambda_functions/process_leads.lambda_handler
    memorySize: 256
    timeout: 30
    environment:
      MIN_SCORE: 0.6

  store-leads:
    handler: lambda_functions/store_leads.lambda_handler
    memorySize: 256
    timeout: 60
    environment:
      AIRTABLE_API_KEY: ${ssm:/bdr-pipeline/airtable-api-key}
      AIRTABLE_BASE_ID: ${ssm:/bdr-pipeline/airtable-base-id}
      AIRTABLE_TABLE_NAME: Leads

  generate-emails:
    handler: lambda_functions/generate_emails.lambda_handler
    memorySize: 512  # More memory for OpenAI API calls
    timeout: 120
    environment:
      OPENAI_API_KEY: ${ssm:/bdr-pipeline/openai-api-key}

  send-emails:
    handler: lambda_functions/send_emails.lambda_handler
    memorySize: 256
    timeout: 120
    environment:
      SENDER_EMAIL: ${ssm:/bdr-pipeline/sender-email}

  # Manual trigger function
  run-pipeline:
    handler: lambda_functions/run_pipeline.lambda_handler
    memorySize: 256
    timeout: 300
    events:
      - http:
          path: /run-pipeline
          method: post
          cors: true

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: false
    layer:
      name: python-deps
      description: Python dependencies for BDR pipeline
    noDeploy:
      - coverage
      - pytest
